#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json
blacklist = ["scratch"]
cache = false
dir_length = 2

sort_order = ["tmux", "config", "zoxide"]

# Windows

[[window]]
name = "shell"

[[window]]
name = "opencode"
startup_script = "opencode"

# Sessions

[[session]]
name = "doitpay-pg"
path = "~/Developer/doitpay/doitpay-pg"
startup_command = "nvim"
preview_command = "eza --all --git --icons --color=always {}"
windows = ["opencode", "shell"]

[[session]]
name = "doitpay-mobi"
path = "~/Developer/doitpay/doitpay-mobi"
startup_command = "nvim"
preview_command = "eza --all --git --icons --color=always {}"
windows = ["opencode", "shell"]

[[session]]
name = "qa-automation"
path = "~/Developer/doitpay/qa-automation"
startup_command = "nvim"
preview_command = "eza --all --git --icons --color=always {}"
windows = ["opencode", "shell"]

[[session]]
name = "okeke-internal"
path = "~/Developer/project/okeke-internal-system/"
startup_command = "nvim"
preview_command = "eza --all --git --icons --color=always {}"
windows = ["opencode", "shell"]

[[session]]
name = "tmuxconf"
path = "~/dotfiles/tmux/.config/tmux"
startup_command = "nvim ."
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "nvimconf"
path = "~/dotfiles/nvim/.config/nvim"
startup_command = "nvim ."
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "seshconf"
path = "~/dotfiles/sesh/.config/sesh"
startup_command = "nvim ."
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "occonf"
path = "~/.config/opencode/"
startup_command = "nvim"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "zshconf"
path = "~"
startup_command = "nvim ~/.zshrc"
preview_command = "bat --color=always ~/.zshrc"
