# First remove *all* keybindings
# unbind-key -a
# Now reinsert all the regular tmux keys

# Session
bind-key "T" display-popup -E -w 80% -h 70% -d '#{pane_current_path}' -T 'Sesh' tv sesh
bind -N "last-session (via sesh) " L run-shell "sesh last"
bind ^X lock-server
bind ^D detach
bind S choose-session
bind ^L refresh-client
bind N new-session
bind X confirm-before -p "kill-session #S? (y/n)" kill-session

# Window
bind w new-window -c "$HOME"
bind ^W list-windows
bind ^A last-window
bind '"' choose-window
# bind -r H previous-window
# bind -r L next-window
bind r command-prompt "rename-window %%"
bind x confirm-before -p "kill-window #W? (y/n)" kill-window
bind | split-window
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind -r ^E rotate-window 
bind -r ^Space next-layout

# Sourcing
bind R source-file ~/.tmux.conf

# Panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r -T prefix , resize-pane -L 5
bind -r -T prefix . resize-pane -R 5
bind -r -T prefix - resize-pane -D 5
bind -r -T prefix = resize-pane -U 5
bind P set pane-border-status
bind c kill-pane
bind * setw synchronize-panes
bind z resize-pane -Z

# Terminal utils
bind K send-keys "clear" Enter
bind -T copy-mode-vi v send-keys -X begin-selection
